services:
  frontend:
    build: ./frontend
    environment:
      STRAPI_TOKEN: foo
      STRAPI_API_URL: http://localhost:1337

    ports:
      - "8000:8000"
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      HOST: 0.0.0.0
      PORT: 1337
      #CLIENT_URL: http://localhost:3000
      #STRAPI_ADMIN_CLIENT_URL: http://localhost:3000
      #STRAPI_ADMIN_CLIENT_PREVIEW_SECRET: USGmBGempHrQ9Bu5DhNXBFxa
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapipassword
      NODE_ENV: ${NODE_ENV}
    ports:
      - "1337:1337"
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    platform: linux/amd64
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapipassword
      POSTGRES_DB: strapi
    volumes:
      - strapi-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  strapi-data:
